#pragma config(Sensor, in2,    potArm,         sensorPotentiometer)
#pragma config(Sensor, in3,    potFlipFlop,    sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           mogoL,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rollers,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           dl1,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           dl2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           arm,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armR1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           dr1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           dr2,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           flipflop,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mogoR,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#define vexCompetitionState (nVexRCReceiveState & (vrDisabled | vrAutonomousMode))

void pre_auton(){

}

int computeActualValue(int val){
	if (abs(val) > 30){
		return val;
	}
	return 0;
}

task drive{
	int forward;
	int turn;
	while (true){
		forward = computeActualValue(vexRT[Ch3]);
		turn = computeActualValue(vexRT[Ch1]);
		motor[dl1] = forward + turn;
		motor[dl2] = forward + turn;
		motor[dr1] = forward - turn;
		motor[dr2] = forward - turn;
	}
}

task armtask {
	while (true){
		if (vexRT[Btn8U]){
			motor[arm] = 127;
			while (vexRT[Btn8U]){

			}
			motor[arm] = 10;
		}
		if (vexRT[Btn8D]){
			motor[arm] = -127;
			while (vexRT[Btn8D]){

			}
			motor[arm] = 0;
		}
	}
}

task autonomous{

}

task usercontrol(){
	startTask(drive);
	startTask(armtask);
}
